### ISSUE TITLE
application crash after switching view from terminal

### ISSUE THREAD

**Issue by LucaFeger** [matthiaaas/ftp#7]
If you open an SSH connection to an SFTP Server and then navigate to the terminal view, the app crashes after selecting any other view.

**Comment by matthiaaas** [comment]
So due to the server settings you had no access to the terminal?

**Comment by LucaFeger** [comment]
Exactly. It was a user account restricted to only use the sftp server.

**Comment by matthiaaas** [comment]
fixed in fbf3c41
